make:
	g++ -std=c++17 -Iinclude src/pendulum.cpp -Llib -lsimulacra -o pendulum -lmatplot
	g++ -std=c++17 -Iinclude src/pendulum_delta.cpp -Llib -lsimulacra -o pendulum_delta -lmatplot
	g++ -std=c++17 -Iinclude src/pendulum_phase_space.cpp -Llib -lsimulacra -o pendulum_phase_space -lmatplot
	g++ -std=c++17 -Iinclude src/pendulum_poincare.cpp -Llib -lsimulacra -o pendulum_poincare -lmatplot


